# Generated by Django 4.1.1 on 2023-01-05 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('base', '0006_alter_hotel_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelloPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('text', models.CharField(max_length=256)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pluginmodel', to='base.hotel')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
